"""clean initial migration setup

Revision ID: 5cf9b410db15
Revises: 
Create Date: 2026-06-10 12:13:50.592562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf9b410db15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_versions', 'accuracy',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_versions', 'accuracy',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    # ### end Alembic commands ###
