# docker-compose.dev.yml
services:
  api:
    env_file:
      - .env.dev          # ← ini yang membuat variable masuk ke container
    volumes:
      - ./app:/app/app
      - ./app/model:/app/model
    ports:
      - "8000:8000"
    restart: "no"

  redis:
    ports:
      - "6379:6379"
    restart: "no"