# Menggunakan image Python yang ringan
FROM python:3.10-slim

# Menyiapkan direktori kerja di dalam container
WORKDIR /app

# Menyalin file requirements dan menginstal dependensi
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Menyalin seluruh kode sumber ke dalam container
COPY . .

# Mengekspos port default Streamlit
EXPOSE 8501

# Perintah untuk menjalankan Streamlit
CMD ["streamlit", "run", "app/frontend/streamlit_app.py", "--server.address=0.0.0.0"]